language: java
sudo: false # faster builds

script: "mvn cobertura:cobertura"

jdk:
  - oraclejdk8
script: mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 8dcf4aacbd7c5a98e11f2f2694e082c7495d0438
  local_dir: target/cucumber/cucumber-html-report
  on:
    branch: master
