language: java
sudo: false # faster builds

script: "mvn cobertura:cobertura"

jdk:
  - oraclejdk8
script: mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 745e059656edf06d5c41bf73b1232bdcf3521e89
  local_dir: target/cucumber/cucumber-html-report
  on:
    branch: master
